anyenv:
  dir:         '{{ home_path }}/.anyenv'
  plugins_dir: '{{ home_path }}/.anyenv/plugins'
  envs_dir:    '{{ home_path }}/.anyenv/envs'
  libexec_dir: '{{ home_path }}/.anyenv/libexec'
  
homebrew:
  taps:
    - homebrew/bundle
    - homebrew/cask
    - homebrew/cask-fonts
    - homebrew/core

  applications:
    - adoptopenjdk8
    - adoptopenjdk14
    - alfred
    - docker
    - google-japanese-ime
    - iterm2
    - jetbrains-toolbox
    - karabiner-elements
    - visual-studio-code
    - google-chrome

  packages:
    - docker
    - fish
    - ffmpeg
    - git
    - vim

mas:
  applications:
    - '497799835' #Xcode
    - '803453959' #Slack
    - '441258766' #Magnet

nodejs:
  versions:
    - "12.13.0"


link:
  config/.ansible.cfg:        .ansible.cfg
  git/.gitconfig:             .gitconfig
  git/.gitignore:             .gitignore
  vim/.vimrc:                 .vimrc
  karabiner:                  .config/karabiner
  iterm2:                     .config/iterm2
  fish:                       .config/fish
  omf:                        .config/omf