- name:       kouki development environment
  hosts:      127.0.0.1
  connection: local

  vars:
    home_path:     '{{ lookup("env", "HOME") }}'
    dotfiles_path: '{{ home_path }}/dotfiles'
    brew_bin_path: '/opt/homebrew/bin'

  roles:
    #  basic
    #-----------------------------------------------
    - role: link
      tags: ['basic', 'basic.link']

    # install 
    #-----------------------------------------------
    # - role: homebrew
    #   tags: ['install', 'install.homebrew']
    # - role: mas
    #   tags: ['install', 'install.mas']

    # lang
    #-----------------------------------------------
    - role: anyenv
      tags: ['lang', 'lang.anyenv']